apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  nodejsping-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - nodejsping.vaayadi.in
    secretName: letsencrypt-prod
  rules:
  - host: nodejsping.vaayadi.in
    http:
      paths:
      - backend:
          serviceName: nodejsping
          servicePort: 80