apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  cloudtorrent-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - cloudtorrent.vaayadi.in
    secretName: letsencrypt-pod
  rules:
  - host: cloudtorrent.vaayadi.in
    http:
      paths:
      - backend:
          serviceName: cloudtorrent
          servicePort: 80